### PR TITLE
 Changed a list of configuration files, now ADPcoWin builds with area…

### PR DESCRIPTION
**Pull request by oksanagit**
…Detector top level and epics-base7: libraries and sampleIOC

Hi,
I have edited  build config files. sampleIOC didn't build for me.  I have copied configs from other ADxx drivers to address compiler complains . sampleIOC builds and produces an executable now! The question is will this still build for Diamond? No st.cmd tests yet.

### CODE REVIEW

**Comment by oksanagit** [comment]
And no errors from Makefile that builds the IOC application with asyn.dbd, busySupport.dbd, etc. explicitly specified in it.

**Comment by BenBradnick** [comment]
We use a custom branch for our build environment at Diamond, so it isn't crucial to make the master branch build for us - plus I think it's a good idea to keep the build configurations consistent across Area Detector modules (as you have done).

**Comment by oksanagit** [comment]
I have made some modifications . st.cmd runs without errors.  It would be nice if Ulrik or Mark could review and merge. There are two connect/configure/init calls: pcoConfig() and pcoApiConfig(). It would be nice to add more elaborate description to what parameters they take and what they do, like in other drivers.

**Comment by MarkRivers** [comment]
I'm not sure what happened.  I had made a number of the changes you have made, for example to
iocs/pcowinIOC/configure/RELEASE
but when it was called pcocam2IOC.  Ben seems to have replaced my versions with more obsolete versions, that you have now had to fix again.

**Comment by oksanagit** [comment]
Added sc2_cl_me4.dll  to .../src/dll64/ 
Also, .../src/ has lib64/ dll/ dll64/ folders. Since there is no lib/ folder, maybe we should remove dll? Who is using 32 bit systems nowadays?  Or add lib/ for 32 bit support?

**Comment by BenBradnick** [comment]
We only use the 64 bit build at Diamond, so feel free to remove the 32 bit libraries.

**Comment by oksanagit** [comment]
Hi @MarkRivers , Could you merge this one as well or comment.  I have pulled the latest master and changed st.cmd and pco.template. This  should fix #1  .

**Pull request merged**
