### PR TITLE
ADPcoWin renaming and example IOC

### PR DESCRIPTION
**Pull request by BenBradnick**
This includes the commits which renamed the contents of the module from pcocam2 to ADPcoWin (I will close the other pull request), and now also has an example Windows IOC (builds on Windows Server 2008 with Visual Studio 2010, and IOC successfully runs on Windows Server 2012 with pco.edge 5.5 CLHS):

- Requires ADCore and Asyn to be defined in RELEASE file for the module
- IOC requires Busy in its RELEASE file
- Then I needed to define ADCORE inside the st.cmd script

### CODE REVIEW

**Comment by MarkRivers** [comment]
It looks like the Makefile that builds the IOC application is including asyn.dbd, busySupport.dbd, etc.  These will be included by commonDriverMakefile which will cause an error on recent versions of base.  I have not actually tested this however.

**Comment by BenBradnick** [comment]
Unfortunately I'm only able to test this on R3.14.12.3 - I can remove those lines if you wish (unless you want to test first?).

**Comment by oksanagit** [comment]
I would like to test first. I have build Support, Core, and ADPcoWin libraries and ready to try.

**Comment by oksanagit** [comment]
I guess it needs to be merged for me to pull.

**Comment by MarkRivers** [comment]
I merged it. I’ll fix any problems when I get back from a trip on Monday, or I can help with some problems remotely.

**Pull request merged**
